### ISSUE TITLE
Reading feature code remotely in radar-pipeline

### ISSUE THREAD

**Issue by Hsankesara** [RADAR-base/radarpipeline#21]
Since now all the feature pipeline will be catalogued and stored in RADAR-base Analytics, we need to add a functionality to read the features code remotely. This would require us to decide how the feature will be stored and what would be the best way to fetch them.

**Comment by Hsankesara** [comment]
@thepushkarp @afolarin  what are your thoughts on this?

**Comment by thepushkarp** [comment]
I think a naive way to do it would be to store the code for each feature as a repo and load them as a submodule when they are required. This would need too many small repos, and would make all the features harder to track.

A more organized way can be to have repos for feature groups and each feature group repo would have codes for the features of that group. When a user requires a feature, the project would fetch that feature group as a submodule and use the particular feature from it that the user needs.

**Comment by afolarin** [comment]
I would steer away from the git-submodule idea -- I don't think it would be fit for this case.

But some composition of modules in a "pipeline project" or similar would be good. Initially, I was considering leaving this to the end user to manage but formalising it sounds like a good idea.

**Comment by afolarin** [comment]
>Since now all the feature pipeline will be catalogued and stored in RADAR-base Analytics, we need to add a functionality to read the features code remotely. This would require us to decide how the feature will be stored and what would be the best way to fetch them.

Gets a little tricky as would need to generalise over yet-to-be-invented feature pipeline outputs.

**Comment by Hsankesara** [comment]
Definitely, I think every feature-group (for example, all the features from a paper)  would be in a single repo. This would make it easier for researchers to make the repo (and their paper) citable. If the repo is open-source, I think we can read it remotely without any issues. But let's discuss, in our next meeting,  if there's a way to formalize it without losing the flexibility.
