### ISSUE TITLE
Fix datatype inconsistencies in pyspark

### ISSUE THREAD

**Issue by thepushkarp** [RADAR-base/radarpipeline#24]
Currently, pyspark is unable to automatically read `double` or `float` numbers in a scientific format directly as `double` or `float`, so they are being read as a `string` datatype.

Add a post-processing function to change datatypes as per the schema after data ingestion.

**Comment by Hsankesara** [comment]
Hmm, that's a weird bug. Do you know why PySpark would do that?

**Comment by thepushkarp** [comment]
I saw this occur when I was reading all of the data together. But currently, we are reading data file by file, so each data frame is small and it is being read correctly. I'll rerun after changing the current implementation to read all the files together and then report the findings.

**Comment by thepushkarp** [comment]
So, right now, I cannot see any such inconsistency, after reading all data at once (#26). Maybe I was doing something off earlier. However, there are still a few improvements such as converting boolean values to boolean values in the dataframe too (currently being read as a string as the data has `false`, but Python recognizes the same boolean as `False`).

**Comment by thepushkarp** [comment]
I have changed this datatype for boolean fields in the schema to use `BooleanType()` by default instead of the previously used `StringType()` when reading the data.

Weirdly, for some data, it still shows the data type read as `string`, while for the rest it shows `string`. Nothing is breaking through, and when exporting both the data into CSVs, the boolean columns were similar, so nothing different in the data.

This behaviour needs further investigation. For the time being, since it is not breaking anything, I think we can continue with other development tasks and come back to it later.

**Comment by afolarin** [comment]
> I have changed this datatype for boolean fields in the schema to use `BooleanType()` by default instead of the previously used `StringType()` when reading the data.
> 
> Weirdly, for some data, it still shows the data type read as `string`, while for the rest it shows `string`. Nothing is breaking through, and when exporting both the data into CSVs, the boolean columns were similar, so nothing different in the data.
> 
> This behaviour needs further investigation. For the time being, since it is not breaking anything, I think we can continue with other development tasks and come back t
I wonder if this might be something to do with schema evolution (just a guess) @yatharthranjan @blootsvoets maybe have something to say here.

Probably ingest should generate a warning

**Comment by thepushkarp** [comment]
> Probably ingest should generate a warning

In the PR #55, we have added a warning whenever a datatype is not among one of those supported, or when there are conflicts and the pipeline falls back to using String type.

**Comment by thepushkarp** [comment]
Solved in #55
