### ISSUE TITLE
Error handling when some features cannot be computed

### ISSUE THREAD

**Issue by Hsankesara** [RADAR-base/radarpipeline#41]
Need to handle the cases where some of the mentioned features cannot be computed. It could be because of the lack of data or some other error in the code.

**Comment by ashishpetwal** [comment]
Can you elaborate more about this, that what actually is happening?

**Comment by Hsankesara** [comment]
In essence, we are creating a data processing and feature generation pipeline for our platform. We have created a feature-group, which is basically a group of multiple features. Therefore, there can be a case where some of the features in that feature group could not be computed because of the lack of data or some other reasons. Therefore, we need error handling to log which feature cannot be computed and compute all the remaining one. I would recommend checkout the wiki if you want to know more or ask questions in the discussion.
