### ISSUE TITLE
Using multiple source data directory during data ingestion

### ISSUE THREAD

**Issue by Hsankesara** [RADAR-base/radarpipeline#42]
Add a feature to have more than one source data directory in the config file. Sometimes researchers might need to read multiple data files to come up with a feature. This might require us to make substantial refactoring in our code.

**Comment by afolarin** [comment]
Yes, I agree this is actually a fairly common scenario. A number of options I guess exist.
1. handled on the user side. User creates a combined dataset folder manually 
2. handled on radarpipeline side
    1. read as two separate datasets (the user then in the analysis code handles the combination of the data)
    2. combines the two separate datasets into one

**Comment by Hsankesara** [comment]
I think we can combine it on our side when there are multiple radar datasets. And anything outside that (like an extra file or directory), the researcher has to define it in the feature module itself.

**Comment by afolarin** [comment]
Let's have a discussion on this. Feels like a bit of a gotchya... and if we need to refactor probably better to do it now rather than later.
