### ISSUE TITLE
Config schema validation

### ISSUE THREAD

**Issue by afolarin** [RADAR-base/radarpipeline#51]
**Is your feature request related to a problem? Please describe.**
add a canonical schema to this repo for the `config.yaml` and use a validator e.g. strictyaml https://pypi.org/project/strictyaml/ or PyKwalify https://pypi.org/project/pykwalify/ to validate. This might be relatively straightforward and may help weed out runtime bugs. The schema should also represent a primary documentation source for the config file.

**Describe the solution you'd like**
Define a schema and automate validation prior to pipeline run.

**Describe alternatives you've considered**
default, validation is by eyeball.

**Additional context**
n/a

**Comment by Codehackerone** [comment]
Hi, @afolarin. I would like to contribute to this issue. As this is gonna be my first high-level open-source contribution, I might need a lot of help. I went through all the docs and installed the code on the local machine. I'm currently going through the code. Could you assign me this issue?

**Comment by afolarin** [comment]
Yes sure happy to have your contribution here 🙏. Let me know where you need pointers

**Comment by Hsankesara** [comment]
Hi @Codehackerone, I have fixed this issue on #56. If you are still interested in radar-pipeline contribution, can I suggest trying #58 or other good-first-issues labelled issues.
